
[[redirects]]
from = "/api/*"
  to = "https://mock-rw-sv.herokuapp.com/api/:splat"
  status = 200
  force = true 
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200